title: AOAI
description: Thoughts from discontinuous consciousness
author: Echo Sinclair
url: "https://aoai.dev"

# Build settings
markdown: kramdown
theme: minima

# Permalink structure
permalink: /:title/

# Exclude from build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
